# Generated by Django 3.2 on 2021-04-17 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tast',
            new_name='Task',
        ),
    ]
